# Generated by Django 3.2.5 on 2021-07-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbook_sports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_logo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
