# Generated by Django 3.2.5 on 2021-07-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbook_sports', '0002_alter_team_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_logo',
            field=models.ImageField(default='soccer.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='profile.png', upload_to='images/'),
        ),
    ]
