# Generated by Django 2.2 on 2021-07-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbook_sports', '0003_auto_20210727_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_logo',
            field=models.ImageField(default='images/soccer.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='images/profile.png', upload_to='images/'),
        ),
    ]
