# Generated by Django 2.2 on 2021-07-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbook_sports', '0004_auto_20210728_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_team_name', models.CharField(max_length=255)),
                ('schedule_team_sport', models.CharField(max_length=255)),
                ('schedule_date', models.DateTimeField()),
                ('schedule_opponent', models.CharField(max_length=255)),
            ],
        ),
    ]
