# Generated by Django 2.2 on 2021-07-29 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playbook_sports', '0004_auto_20210729_1318'),
        ('playbook_sports', '0005_schedule'),
    ]

    operations = [
    ]
