# Generated by Django 2.2 on 2021-07-30 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playbook_sports', '0006_merge_20210729_2035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
